# Generated by Django 3.1.5 on 2021-01-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "caption",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("image", models.ImageField(upload_to="img/%y")),
                (
                    "created_at_utc",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("modified_at_utc", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "db_table": "Image",
                "ordering": ("-created_at_utc",),
            },
        ),
    ]
